jspm is added
samiheikki/javascript-guessing-game pull request #31
Opened 2016-11-09 11:36 UTC by Navajyoth

jspm is a package manager for the SystemJS universal module loader, built on top of the dynamic ES6 module loader

2016-11-09 12:41 UTC, samiheikki requested changes
Hi @Navajyoth Thanks for the PR 🎉 

Can you maintain the alphabetic order in logos.json (Jspm comes before JSX). After that, I can happily merge the PR 😄

2016-11-09 12:41 UTC, samiheikki commented on static/logos.json
> +    "name": "Jspm"
Move this before JSX. Jspm comes before JSX

2016-11-10 12:59 UTC, samiheikki commented
This also needs rebase. Do you want to do it @Navajyoth or want me to take it from here?

2016-11-17 07:17 UTC, Navajyoth commented on static/logos.json
> +    "name": "Jspm"
I dont have permission to update issue ?. Can you make it available to me ?

2016-11-17 07:25 UTC, Navajyoth commented
jspm alphabetical order issue fixed.

2016-11-17 07:28 UTC, samiheikki approved these changes

2016-11-17 07:28 UTC, merged

2016-11-17 07:28 UTC, samiheikki commented
Thanks @Navajyoth 🎉