Haul
samiheikki/javascript-guessing-game pull request #89
Opened 2017-04-03 14:04 UTC by zoltantothcom

[Haul](https://github.com/callstack-io/haul) is a command line tool for developing React Native apps

2017-04-03 16:51 UTC, samiheikki requested changes

2017-04-03 16:51 UTC, samiheikki commented on static/logos.json
> +    "name": "Haul"
Should be after Handlebars

2017-04-03 17:02 UTC, zoltantothcom commented on static/logos.json
> +    "name": "Haul"
Dammit! My usual struggle with the alphabet! :)
Fixing now..

2017-04-04 04:43 UTC, samiheikki approved these changes

2017-04-04 04:44 UTC, merged